loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
  persistence:
    enabled: ${persistence_enabled}
    size: ${persistence_size}
  retentionConfig:
    retention_period: ${retention_period}