name: Deploy to Dev

on:
  push:
    branches: [main]
    paths:
      - 'environments/dev/**'
      - 'modules/**'

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: write
      id-token: write  # For AWS OIDC auth

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS Credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_IAM_ROLE_DEV }}
        aws-region: us-east-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform-version: 1.8.0

    - name: Terraform Init
      run: terraform init -backend-config="environments/dev/backend.hcl"
      working-directory: environments/dev

    - name: Terraform Plan
      run: terraform plan
      working-directory: environments/dev

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: environments/dev