name: Deploy to Prod

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [main]
    paths:
      - 'environments/prod/**'
      - 'modules/**'

jobs:
  plan:
    runs-on: ubuntu-latest
    environment: prod-plan
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_IAM_ROLE_PROD }}
        aws-region: us-east-1

    - uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init -backend-config="environments/prod/backend.hcl"
      working-directory: environments/prod

    - name: Terraform Plan
      run: terraform plan -no-color -input=false
      working-directory: environments/prod

    - name: Upload Plan Artifact
      uses: actions/upload-artifact@v4
      with:
        name: tf-plan
        path: environments/prod/plan.out

  apply:
    needs: plan
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_IAM_ROLE_PROD }}
        aws-region: us-east-1

    - uses: hashicorp/setup-terraform@v3

    - name: Download Plan Artifact
      uses: actions/download-artifact@v4
      with:
        name: tf-plan

    - name: Manual Approval
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ secrets.PROD_APPROVAL_TOKEN }}
        approvers: "devops-team"

    - name: Terraform Apply
      run: terraform apply -auto-approve plan.out
      working-directory: environments/prod